import Service1 from "@/public/images/services/jamie-street-ikv10lHZUas-unsplash.jpg";
import Service2 from "@/public/images/services/roberto-nickson-ey5s8rNHG-c-unsplash.jpg";

export const services = [
  {
    title: "PET SPA",
    desc: "Chúng tôi mang đến dịch vụ tắm gội dịu nhẹ, cắt tỉa tạo kiểu, massage thư giãn, vệ sinh răng miệng và cắt móng, không gian sạch sẽ hiện đại và đội ngũ giàu kinh nghiệm.",
    img: Service1,
  },
  {
    title: "PET HOTEL",
    desc: "Dịch vụ khách sạn thú cưng tiện nghi, an toàn và thân thiện. Thú cưng của bạn sẽ được chăm sóc chu đáo như ở nhà.",
    img: Service2,
  },
];

export const hotelServices = [
  {
    id: "room1",
    title: "Luxury Suite",
    subtitle: "Phòng rộng rãi, giường êm, view đẹp.",
    price: "Từ 500.000đ/đêm",
    img: "/images/hotel1.jpg",
  },
  {
    id: "room2",
    title: "Standard Room",
    subtitle: "Tiện nghi đầy đủ, an toàn cho thú cưng.",
    price: "Từ 300.000đ/đêm",
    img: "/images/hotel2.jpg",
  },
  {
    id: "room3",
    title: "Family Room",
    subtitle: "Không gian cho nhiều bé cùng lúc, vui chơi thoải mái.",
    price: "Từ 700.000đ/đêm",
    img: "/images/hotel3.jpg",
  },
  {
    id: "room4",
    title: "Family Room",
    subtitle: "Không gian cho nhiều bé cùng lúc, vui chơi thoải mái.",
    price: "Từ 700.000đ/đêm",
    img: "/images/hotel4.jpg",
  },
  {
    id: "room5",
    title: "Family Room",
    subtitle: "Không gian cho nhiều bé cùng lúc, vui chơi thoải mái.",
    price: "Từ 700.000đ/đêm",
    img: "/images/hotel5.jpg",
  },
  {
    id: "room6",
    title: "Family Room",
    subtitle: "Không gian cho nhiều bé cùng lúc, vui chơi thoải mái.",
    price: "Từ 700.000đ/đêm",
    img: "/images/hotel6.jpg",
  },
];

export const cardVariants = {
  hidden: { opacity: 0, y: 40 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.15, duration: 0.8, ease: "easeOut" as const },
  }),
};

import {
  Bath,
  Gamepad2,
  LucideBath,
  LucideDog,
  LucideGraduationCap,
  LucideHome,
  LucideStethoscope,
  LucideTruck,
  Shirt,
  Utensils,
} from "lucide-react";
export const productCategories = [
  {
    id: "food",
    title: "Thức ăn & Dinh dưỡng",
    subtitle: "Thức ăn cao cấp, snack, vitamin cho thú cưng",
    icon: Utensils,
    products: [
      {
        name: "Royal Canin Adult Dog Food",
        price: "850.000đ",
        originalPrice: "950.000đ",
        rating: 4.8,
        reviews: 245,
        image: "/images/product_1.jpg",
        description:
          "Thức ăn cao cấp cho chó trưởng thành, cân bằng dinh dưỡng",
        features: [
          "Protein cao",
          "Omega 3&6",
          "Hỗ trợ tiêu hóa",
          "Made in France",
        ],
      },
      {
        name: "Whiskas Cat Food Tuna",
        price: "320.000đ",
        originalPrice: "380.000đ",
        rating: 4.6,
        reviews: 189,
        image: "/images/product_2.jpg",
        description: "Thức ăn ướt cho mèo vị cá ngừ, bổ sung nước",
        features: [
          "Cá ngừ tươi",
          "Vitamin E",
          "Taurine",
          "Không chất bảo quản",
        ],
      },
      {
        name: "Pedigree Dentastix",
        price: "180.000đ",
        originalPrice: "220.000đ",
        rating: 4.7,
        reviews: 156,
        image: "/images/product_3.jpg",
        description: "Snack chăm sóc răng miệng cho chó",
        features: [
          "Làm sạch răng",
          "Giảm cao răng",
          "Hương vị thịt",
          "Dễ tiêu hóa",
        ],
      },
    ],
  },
  {
    id: "grooming",
    title: "Vệ sinh & Làm đẹp",
    subtitle: "Sản phẩm tắm gội, cắt tỉa, chăm sóc lông",
    icon: Bath,
    products: [
      {
        name: "Bio-Groom Protein Lanolin Shampoo",
        price: "450.000đ",
        originalPrice: "520.000đ",
        rating: 4.9,
        reviews: 98,
        image: "/images/product_4.jpg",
        description: "Dầu gội cao cấp với protein và lanolin",
        features: [
          "Protein tự nhiên",
          "Làm mềm lông",
          "pH cân bằng",
          "Không gây kích ứng",
        ],
      },
      {
        name: "Kìm cắt móng Millers Forge",
        price: "280.000đ",
        originalPrice: "350.000đ",
        rating: 4.8,
        reviews: 134,
        image: "/images/product_5.jpg",
        description: "Kìm cắt móng chuyên nghiệp, an toàn",
        features: [
          "Thép không gỉ",
          "Tay cầm chống trượt",
          "Cắt sạch sẽ",
          "Bảo hành 2 năm",
        ],
      },
      {
        name: "Lược chải lông FURminator",
        price: "680.000đ",
        originalPrice: "780.000đ",
        rating: 4.9,
        reviews: 267,
        image: "/images/product_6.jpg",
        description: "Lược chải lông chuyên nghiệp, giảm rụng lông",
        features: [
          "Công nghệ đặc biệt",
          "Giảm 90% rụng lông",
          "Tay cầm ergonomic",
          "Phù hợp mọi giống",
        ],
      },
    ],
  },
  {
    id: "toys",
    title: "Đồ chơi & Giải trí",
    subtitle: "Đồ chơi thông minh, bóng, dây thừng cho thú cưng",
    icon: Gamepad2,
    products: [
      {
        name: "Kong Classic Dog Toy",
        price: "320.000đ",
        originalPrice: "380.000đ",
        rating: 4.8,
        reviews: 445,
        image: "/images/product_7.jpg",
        description: "Đồ chơi cao su tự nhiên, kích thích trí tuệ",
        features: [
          "Cao su tự nhiên",
          "Nhồi snack được",
          "Kích thích IQ",
          "Siêu bền",
        ],
      },
      {
        name: "Feather Wand Cat Toy",
        price: "150.000đ",
        originalPrice: "200.000đ",
        rating: 4.7,
        reviews: 189,
        image: "/images/product_8.jpg",
        description: "Đồ chơi lông vũ tương tác cho mèo",
        features: [
          "Lông vũ tự nhiên",
          "Cần câu linh hoạt",
          "Kích thích săn mồi",
          "An toàn",
        ],
      },
      {
        name: "Puzzle Feeder Bowl",
        price: "280.000đ",
        originalPrice: "340.000đ",
        rating: 4.6,
        reviews: 123,
        image: "/images/product_9.jpg",
        description: "Bát ăn thông minh, chậm tiêu hóa",
        features: [
          "Ăn chậm",
          "Kích thích tư duy",
          "Chống đầy hơi",
          "Dễ vệ sinh",
        ],
      },
    ],
  },
  {
    id: "accessories",
    title: "Phụ kiện & Trang phục",
    subtitle: "Vòng cổ, dây dắt, quần áo, giường nằm",
    icon: Shirt,
    products: [
      {
        name: "Leather Collar Premium",
        price: "420.000đ",
        originalPrice: "500.000đ",
        rating: 4.8,
        reviews: 156,
        image: "/images/product_10.jpg",
        description: "Vòng cổ da thật cao cấp, khắc tên miễn phí",
        features: [
          "Da thật 100%",
          "Khắc tên miễn phí",
          "Khóa inox",
          "Nhiều size",
        ],
      },
      {
        name: "Retractable Leash 5m",
        price: "380.000đ",
        originalPrice: "450.000đ",
        rating: 4.7,
        reviews: 234,
        image: "/images/product_11.jpg",
        description: "Dây dắt tự động 5m, chịu lực 50kg",
        features: [
          "Tự động thu dây",
          "Chịu lực 50kg",
          "Tay cầm chống trượt",
          "Khóa an toàn",
        ],
      },
      {
        name: "Orthopedic Pet Bed",
        price: "1.200.000đ",
        originalPrice: "1.450.000đ",
        rating: 4.9,
        reviews: 89,
        image: "/images/product_12.jpg",
        description: "Giường nệm memory foam, hỗ trợ xương khớp",
        features: [
          "Memory foam",
          "Hỗ trợ xương khớp",
          "Vỏ tháo rời",
          "Chống nước",
        ],
      },
    ],
  },
];

export const servicesSpa = [
  {
    id: "spa",
    title: "Spa & Grooming",
    subtitle: "Tắm, cắt tỉa, vệ sinh móng, tạo kiểu lông.",
    icon: LucideBath,
    price: "Từ 250.000đ",
    img: "/images/shower.jpg",
    details: [
      {
        id: "bath-basic",
        name: "Tắm cơ bản",
        description: "Bao gồm tắm gội, sấy khô và chải lông.",
        price: "250.000đ",
        duration: "45 phút",
        img: "/images/spa1.jpg",
      },
      {
        id: "bath-premium",
        name: "Tắm dưỡng da",
        description: "Sử dụng dầu gội hữu cơ, phù hợp da nhạy cảm.",
        price: "400.000đ",
        duration: "60 phút",
        img: "/images/spa2.jpg",
      },
      {
        id: "full-groom",
        name: "Cắt tỉa toàn diện",
        description: "Cắt lông theo kiểu, vệ sinh móng, tai & răng.",
        price: "500.000đ",
        duration: "90 phút",
        img: "/images/spa3.jpg",
      },
      {
        id: "bath-basic2",
        name: "Tắm cơ bản",
        description: "Bao gồm tắm gội, sấy khô và chải lông.",
        price: "250.000đ",
        duration: "45 phút",
        img: "/images/spa1.jpg",
      },
      {
        id: "bath-premium2",
        name: "Tắm dưỡng da",
        description: "Sử dụng dầu gội hữu cơ, phù hợp da nhạy cảm.",
        price: "400.000đ",
        duration: "60 phút",
        img: "/images/spa2.jpg",
      },
      {
        id: "full-groom2",
        name: "Cắt tỉa toàn diện",
        description: "Cắt lông theo kiểu, vệ sinh móng, tai & răng.",
        price: "500.000đ",
        duration: "90 phút",
        img: "/images/spa3.jpg",
      },
    ],
  },
  {
    id: "boarding",
    title: "Boarding (Khách sạn)",
    subtitle: "Chỗ ở tiện nghi, giám sát 24/7, an toàn tuyệt đối.",
    icon: LucideHome,
    price: "Từ 300.000đ/đêm",
    img: "/images/hotel.jpg",
    details: [
      {
        id: "standard-room",
        name: "Phòng tiêu chuẩn",
        description: "Phòng sạch sẽ, thoáng mát, phù hợp thú cưng nhỏ.",
        price: "300.000đ/đêm",
        duration: "Theo đêm",
        img: "/images/hotel1.jpg",
      },
      {
        id: "vip-room",
        name: "Phòng VIP",
        description: "Rộng rãi, có điều hòa và camera theo dõi trực tiếp.",
        price: "500.000đ/đêm",
        duration: "Theo đêm",
        img: "/images/hotel2.jpg",
      },
      {
        id: "luxury-room",
        name: "Phòng Luxury",
        description: "Không gian cao cấp, có sân chơi riêng.",
        price: "800.000đ/đêm",
        duration: "Theo đêm",
        img: "/images/hotel3.jpg",
      },
      {
        id: "standard-room2",
        name: "Phòng tiêu chuẩn",
        description: "Phòng sạch sẽ, thoáng mát, phù hợp thú cưng nhỏ.",
        price: "300.000đ/đêm",
        duration: "Theo đêm",
        img: "/images/hotel1.jpg",
      },
      {
        id: "vip-room2",
        name: "Phòng VIP",
        description: "Rộng rãi, có điều hòa và camera theo dõi trực tiếp.",
        price: "500.000đ/đêm",
        duration: "Theo đêm",
        img: "/images/hotel2.jpg",
      },
      {
        id: "luxury-room2",
        name: "Phòng Luxury",
        description: "Không gian cao cấp, có sân chơi riêng.",
        price: "800.000đ/đêm",
        duration: "Theo đêm",
        img: "/images/hotel3.jpg",
      },
    ],
  },
  {
    id: "daycare",
    title: "Chăm sóc ban ngày",
    subtitle: "Chơi & vận động cho thú cưng trong ngày.",
    icon: LucideDog,
    price: "150.000đ/ngày",
    img: "/images/care.jpg",
    details: [
      {
        id: "half-day",
        name: "Gói nửa ngày",
        description: "Chăm sóc 4 giờ, bao gồm ăn nhẹ và chơi vận động.",
        price: "100.000đ",
        duration: "4 giờ",
        img: "/images/hotel7.jpg",
      },
      {
        id: "full-day",
        name: "Gói cả ngày",
        description: "Chăm sóc trọn ngày, hoạt động vui chơi & giám sát.",
        price: "150.000đ",
        duration: "8 giờ",
        img: "/images/hotel7.jpg",
      },
      {
        id: "playgroup",
        name: "Chơi theo nhóm",
        description: "Cho thú cưng chơi cùng bạn bè, vận động ngoài trời.",
        price: "200.000đ",
        duration: "Cả ngày",
        img: "/images/hotel7.jpg",
      },
      {
        id: "half-day2",
        name: "Gói nửa ngày",
        description: "Chăm sóc 4 giờ, bao gồm ăn nhẹ và chơi vận động.",
        price: "100.000đ",
        duration: "4 giờ",
        img: "/images/hotel7.jpg",
      },
      {
        id: "full-day2",
        name: "Gói cả ngày",
        description: "Chăm sóc trọn ngày, hoạt động vui chơi & giám sát.",
        price: "150.000đ",
        duration: "8 giờ",
        img: "/images/hotel7.jpg",
      },
      {
        id: "playgroup2",
        name: "Chơi theo nhóm",
        description: "Cho thú cưng chơi cùng bạn bè, vận động ngoài trời.",
        price: "200.000đ",
        duration: "Cả ngày",
        img: "/images/hotel7.jpg",
      },
    ],
  },
  {
    id: "training",
    title: "Huấn luyện",
    subtitle: "Obedience, tricks cơ bản & nâng cao.",
    icon: LucideGraduationCap,
    price: "Từ 1.200.000đ/khóa",
    img: "/images/train.jpg",
    details: [
      {
        id: "basic-training",
        name: "Huấn luyện cơ bản",
        description: "Ngồi, nằm, bắt tay, gọi tên, đi cạnh chủ.",
        price: "1.200.000đ/khóa",
        duration: "4 tuần",
        img: "/images/train1.jpg",
      },
      {
        id: "advanced-training",
        name: "Huấn luyện nâng cao",
        description: "Kỹ năng nâng cao, hành vi tốt trong xã hội.",
        price: "2.500.000đ/khóa",
        duration: "6 tuần",
        img: "/images/train2.jpg",
      },
      {
        id: "trick-training",
        name: "Huấn luyện biểu diễn",
        description:
          "Học tricks vui nhộn: xoay vòng, bắt đồ chơi, nhảy qua vòng.",
        price: "3.000.000đ/khóa",
        duration: "6 tuần",
        img: "/images/train3.jpg",
      },
      {
        id: "basic-training2",
        name: "Huấn luyện cơ bản",
        description: "Ngồi, nằm, bắt tay, gọi tên, đi cạnh chủ.",
        price: "1.200.000đ/khóa",
        duration: "4 tuần",
        img: "/images/train1.jpg",
      },
      {
        id: "advanced-training2",
        name: "Huấn luyện nâng cao",
        description: "Kỹ năng nâng cao, hành vi tốt trong xã hội.",
        price: "2.500.000đ/khóa",
        duration: "6 tuần",
        img: "/images/train2.jpg",
      },
      {
        id: "trick-training2",
        name: "Huấn luyện biểu diễn",
        description:
          "Học tricks vui nhộn: xoay vòng, bắt đồ chơi, nhảy qua vòng.",
        price: "3.000.000đ/khóa",
        duration: "6 tuần",
        img: "/images/train3.jpg",
      },
    ],
  },
  {
    id: "vet",
    title: "Khám & Tiêm chủng",
    subtitle: "Bác sĩ thú y tận tình, dịch vụ y tế toàn diện.",
    icon: LucideStethoscope,
    price: "Khám: 200.000đ",
    img: "/images/medical.jpg",
    details: [
      {
        id: "health-check",
        name: "Khám sức khỏe tổng quát",
        description: "Kiểm tra tổng thể, tư vấn dinh dưỡng.",
        price: "200.000đ",
        duration: "30 phút",
        img: "/images/medical1.jpg",
      },
      {
        id: "vaccination",
        name: "Tiêm phòng",
        description: "Các loại vaccine cơ bản & nâng cao.",
        price: "300.000đ/mũi",
        duration: "15 phút",
        img: "/images/medical2.jpg",
      },
      {
        id: "dental-care",
        name: "Chăm sóc răng miệng",
        description: "Làm sạch răng, ngừa viêm nướu.",
        price: "500.000đ/lần",
        duration: "45 phút",
        img: "/images/medical3.jpg",
      },
      {
        id: "health-check2",
        name: "Khám sức khỏe tổng quát",
        description: "Kiểm tra tổng thể, tư vấn dinh dưỡng.",
        price: "200.000đ",
        duration: "30 phút",
        img: "/images/medical1.jpg",
      },
      {
        id: "vaccination2",
        name: "Tiêm phòng",
        description: "Các loại vaccine cơ bản & nâng cao.",
        price: "300.000đ/mũi",
        duration: "15 phút",
        img: "/images/medical2.jpg",
      },
      {
        id: "dental-care2",
        name: "Chăm sóc răng miệng",
        description: "Làm sạch răng, ngừa viêm nướu.",
        price: "500.000đ/lần",
        duration: "45 phút",
        img: "/images/medical3.jpg",
      },
    ],
  },
  {
    id: "pickup",
    title: "Đón & Trả tận nơi",
    subtitle: "Đưa đón thú cưng tiện lợi, an toàn & nhanh chóng.",
    icon: LucideTruck,
    price: "50.000đ/chuyến",
    img: "/images/travel.jpg",
    details: [
      {
        id: "one-way",
        name: "Đón một chiều",
        description: "Đón từ nhà đến spa/boarding.",
        price: "50.000đ",
        duration: "Theo chuyến",
        img: "/images/travel.jpg",
      },
      {
        id: "round-trip",
        name: "Đón & trả",
        description: "Đưa đón tận nơi cả hai chiều.",
        price: "90.000đ",
        duration: "Theo chuyến",
        img: "/images/travel.jpg",
      },
      {
        id: "vip-pickup",
        name: "Xe riêng VIP",
        description: "Xe riêng, máy lạnh, an toàn tối đa.",
        price: "200.000đ",
        duration: "Theo chuyến",
        img: "/images/travel.jpg",
      },
      {
        id: "one-way2",
        name: "Đón một chiều",
        description: "Đón từ nhà đến spa/boarding.",
        price: "50.000đ",
        duration: "Theo chuyến",
        img: "/images/travel.jpg",
      },
      {
        id: "round-trip2",
        name: "Đón & trả",
        description: "Đưa đón tận nơi cả hai chiều.",
        price: "90.000đ",
        duration: "Theo chuyến",
        img: "/images/travel.jpg",
      },
      {
        id: "vip-pickup2",
        name: "Xe riêng VIP",
        description: "Xe riêng, máy lạnh, an toàn tối đa.",
        price: "200.000đ",
        duration: "Theo chuyến",
        img: "/images/travel.jpg",
      },
    ],
  },
];

export const itemsByCategory = {
  spa: [
    {
      id: "spa1",
      name: "Spa Luxury",
      price: "300.000đ",
      img: "/images/shower.jpg",
      desc: "Spa cao cấp với đầy đủ dịch vụ grooming, massage và chăm sóc da lông.",
    },
    {
      id: "spa2",
      name: "Spa Standard",
      price: "250.000đ",
      img: "/images/shower.jpg",
      desc: "Gói spa cơ bản: tắm, cắt móng, vệ sinh tai.",
    },
  ],
  boarding: [
    {
      id: "hotel1",
      name: "Hotel 5 sao",
      price: "500.000đ/đêm",
      img: "/images/hotel.jpg",
      desc: "Phòng tiện nghi, giám sát 24/7, không gian rộng rãi cho thú cưng.",
    },
    {
      id: "hotel2",
      name: "Hotel tiêu chuẩn",
      price: "300.000đ/đêm",
      img: "/images/hotel.jpg",
      desc: "Gói cơ bản cho thú cưng ở ngắn hạn, chăm sóc đầy đủ.",
    },
  ],
  daycare: [
    {
      id: "daycare1",
      name: "Daycare VIP",
      price: "200.000đ/ngày",
      img: "/images/care.jpg",
      desc: "Chăm sóc ban ngày, vui chơi và vận động cho thú cưng.",
    },
  ],
  training: [
    {
      id: "train1",
      name: "Training cơ bản",
      price: "1.200.000đ/khóa",
      img: "/images/train.jpg",
      desc: "Huấn luyện hành vi, obedience cơ bản cho thú cưng.",
    },
  ],
  vet: [
    {
      id: "vet1",
      name: "Khám & Tiêm chủng cơ bản",
      price: "200.000đ",
      img: "/images/medical.jpg",
      desc: "Khám sức khỏe và tiêm phòng cơ bản.",
    },
  ],
  pickup: [
    {
      id: "pickup1",
      name: "Đón & Trả gần",
      price: "50.000đ/chuyến",
      img: "/images/travel.jpg",
      desc: "Dịch vụ đưa đón thú cưng trong bán kính gần.",
    },
  ],
};

export const productVariants = {
  hidden: { opacity: 0, scale: 0.9 },
  visible: (i: number) => ({
    opacity: 1,
    scale: 1,
    transition: { delay: i * 0.05, duration: 0.4, ease: "easeOut" },
  }),
};
